In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import seaborn as sns

In [2]:
df=pd.read_csv(r"DataSets\student_exam.csv")
df.head()

   study_hours  previous_score  passed_exam
0          2.0              45            0
1          3.0              50            0
2          2.5              55            0
3          4.0              60            0
4          5.0              62            0

In [3]:
df.describe()

       study_hours  previous_score  passed_exam
count    49.000000       49.000000    49.000000
mean      5.761224       67.897959     0.571429
std       2.471910       13.694958     0.500000
min       1.500000       40.000000     0.000000
25%       4.000000       60.000000     0.000000
50%       5.500000       67.000000     1.000000
75%       7.500000       77.000000     1.000000
max      11.000000       95.000000     1.000000

In [ ]:
plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='study_hours',y='previous_score',marker='o',s=100)